name: .NET
 
on:
  push:
    branches: [ master ]

 
jobs:
  build:
 
    runs-on: windows-latest
 
    steps:
    - uses: actions/checkout@v1
      name: Checkout Code
      
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
      env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'     

    - name: Restore NuGet Packages
      run: nuget restore GraphLayout/GraphLayout.sln
 
    - name: Build and Publish Web App
      run: msbuild GraphLayout\tools\agl\agl.csproj /p:Configuration=Release /p:Platform="AnyCPU" /p:DeployOnBuild=true /p:PublishProfile=FolderProfile

    - name: Upload Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: agl_exe_directory
        path: GraphLayout/tools/agl/bin/Release/
        
    - name: Release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        replace: true
        release_name: ${{ steps.version.outputs.version }}
        tag_name: latest
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name : aglzip
      run: 7z  GraphLayout/tools/agl/bin/Release  agl.zip

    - name: artifacts
      uses: ncipollo/release-action@v1
      with:
        artifacts: agl.zip
        token: ${{ secrets.GITHUB_TOKEN }}


        
